import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'
import ItemGallery from '../components/ItemGallery';


export default function Home() {
  const listings: Array<object> = [{
    title: 'Pokemon 1',
  }];
  return (
    <>
      <Head>
        <title>Pokemon Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ItemGallery listings={listings} />
      </main>
    </>
  )
}
