import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import ProductGallery from '../components/ProductGallery';

import products from '../products.json';

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Pokemon Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ProductGallery products={products} />
      </main>
    </>
  )
}
